name: TrenchPvP
main: net.peacefulcraft.trenchpvp.TrenchPvP
version: 1.0
api-version: 1.13

commands:
    tppToggle:
      description: Toggle Trench PvP Game Running State.
      permission: tpp.admin.tppToggle
      usage: /<command> To Toggle Game State
    tppGetGameState:
      description: Get Trench Game state
      permission: tpp.admin.tppGetGameState
      usage: /<command> To Get Game State
    trjoin:
      description: Join Trench
      permission: tpp.player
      usage: /<command> To join game
    trleave:
      description: Leave Trench
      permission: tpp.player
      usage: /<command> To join game
    tppDebug:
      description: Get Trench Debug Information
      usage: /<command>
    tppSet:
      description: Configured Trench Settings
      usage: "/<command> [ blueSpawn | blueClassSpawn | redSpawn | redClassSpawn | quitSpawn | spectatorSpawn ]"