name: TrenchPvP
main: net.peacefulcraft.trenchpvp.TrenchPvP
version: 1.0
api-version: 1.14.4

commands:
    trjoin:
      description: Join Trench
      usage: /<command> To join game
    trleave:
      description: Leave Trench
      usage: /<command> To join game
    tppSet:
      description: Configured Trench Settings
      usage: "/<command> [ blueSpawn | blueClassSpawn | redSpawn | redClassSpawn | quitSpawn | spectatorSpawn ]"
