name: TrenchPvP
main: net.peacefulcraft.trenchpvp.TrenchPvP
version: 1.0
api-version: 1.14

commands:
    trjoin:
      description: Join Trench
      usage: /<command> To join game
    trleave:
      description: Leave Trench
      usage: /<command> To join game
    tra:
      description: Configure Trench Settings
      usage: "/<command>, there are so many options this is not useful"
