trenchspawns:
  quit: {}
  red: {}
  blue: {}
  red_class: {}
  blue_class: {}
  spectator: {}

database:
    ip: "127.0.0.1"
    name: "database name"
    username: "user"
    password: "super secret"
